export const PRODUCT_DETAILS = [
  {
    id: "1",
    slug: "premium-slim-fit-polo-shirt",
    title: "Premium Slim Fit Polo Shirt",
    image: "/images/product1.png",
    images: [
      "/images/product1.png",
      "/images/product2.png",
      "/images/product3.png",
      "/images/product4.png",
    ],
    price: 29.0,
    salePrice: 23.0,
    rating: 5,
    reviews: 121,
    description:
      "Stylish and modern polo made from breathable fabric for all-day wear.",
    colors: ["#ef4444", "#6366f1", "#f59e0b", "#111827", "#22c55e", "#a3e635"],
    sizes: ["S", "M", "L", "XL", "XXL"],
    stock: true,
  },
  {
    id: "8",
    slug: "vintage-washed-denim-shirt",
    title: "Vintage Washed Denim Shirt",
    image: "/images/product2.png",
    images: [
      "/images/product2.png",
      "/images/product1.png",
      "/images/product3.png",
      "/images/product4.png",
    ],
    price: 32.0,
    salePrice: 30.0,
    rating: 4,
    reviews: 89,
    description:
      "Classic denim shirt with a faded wash for a rugged, timeless look.",
    colors: ["#ef4444", "#6366f1", "#f59e0b"],
    sizes: ["S", "M", "L", "XL"],
    stock: true,
  },
  {
    id: "3",
    slug: "casual-oversized-graphic-tee",
    title: "Casual Oversized Graphic Tee",
    image: "/images/product3.png",
    images: [
      "/images/product3.png",
      "/images/product2.png",
      "/images/product1.png",
      "/images/product4.png",
    ],
    price: 24.0,
    salePrice: 20.99,
    rating: 4,
    reviews: 64,
    description:
      "Bold graphic print tee with an oversized fit for a relaxed vibe.",
    colors: ["#ef4444", "#6366f1", "#f59e0b"],
    sizes: ["S", "M", "L", "XL"],
    stock: true,
  },
  {
    id: "4",
    slug: "long-sleeve-henley-shirt",
    title: "Long Sleeve Henley Shirt",
    image: "/images/product4.png",
    images: [
      "/images/product4.png",
      "/images/product3.png",
      "/images/product2.png",
      "/images/product1.png",
    ],
    price: 29.99,
    salePrice: 19.99,
    rating: 4,
    reviews: 71,
    description:
      "Lightweight and comfortable Henley ideal for layering in any season.",
    colors: ["#ef4444", "#6366f1", "#f59e0b"],
    sizes: ["S", "M", "L", "XL"],
    stock: true,
  },
  {
    id: "5",
    slug: "formal-white-dress-shirt",
    title: "Formal White Dress Shirt",
    image: "/images/product5.png",
    images: [
      "/images/product5.png",
      "/images/product6.png",
      "/images/product7.png",
      "/images/product8.png",
    ],
    price: 26.99,
    salePrice: 22.99,
    rating: 5,
    reviews: 103,
    description:
      "Crisp, wrinkle-resistant white shirt tailored for business or events.",
    colors: ["#ef4444", "#6366f1", "#f59e0b", "#111827"],
    sizes: ["S", "M", "L", "XL"],
    stock: true,
  },
  {
    id: "6",
    slug: "soft-flannel-checked-shirt",
    title: "Soft Flannel Checked Shirt",
    image: "/images/product6.png",
    images: [
      "/images/product6.png",
      "/images/product5.png",
      "/images/product7.png",
      "/images/product8.png",
    ],
    price: 30.0,
    salePrice: 27.0,
    rating: 4,
    reviews: 77,
    description:
      "Warm flannel shirt with a traditional checkered pattern for cold days.",
    colors: ["#ef4444", "#6366f1", "#f59e0b"],
    sizes: ["S", "M", "L", "XL"],
    stock: true,
  },
  {
    id: "7",
    slug: "stretch-activewear-t-shirt",
    title: "Stretch Activewear T-Shirt",
    image: "/images/product7.png",
    images: [
      "/images/product7.png",
      "/images/product6.png",
      "/images/product5.png",
      "/images/product8.png",
    ],
    price: 25.99,
    salePrice: 22.99,
    rating: 4,
    reviews: 54,
    description:
      "Flexible, moisture-wicking tee designed for workouts or casual wear.",
    colors: ["#ef4444", "#6366f1", "#f59e0b"],
    sizes: ["S", "M", "L", "XL"],
    stock: true,
  },
  {
    id: "2",
    slug: "linen-short-sleeve-button-up",
    title: "Linen Short Sleeve Button-Up",
    image: "/images/product8.png",
    images: [
      "/images/product8.png",
      "/images/product7.png",
      "/images/product6.png",
      "/images/product5.png",
    ],
    price: 29.0,
    salePrice: 0,
    rating: 4,
    reviews: 58,
    description:
      "Breezy and lightweight linen shirt perfect for summer outings.",
    colors: ["#ef4444", "#6366f1", "#f59e0b"],
    sizes: ["S", "M", "L", "XL"],
    stock: true,
  },
];

export default PRODUCT_DETAILS;
